In [1]:
import torch

import torch.nn as nn
import numpy as np

from torch.optim import SGD

In [9]:
class NeuralNetworkModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.linear1 = nn.Linear(2, 10)
        self.linear2 = nn.Linear(10, 1)

        self.relu = nn.functional.relu
        

    def forward(self, x):
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        x = nn.functional.sigmoid(x)

        return x

In [7]:
inputs = torch.tensor([[2., 32.], [25., 1.2], [5., 25.2], [23., 2.], [56., 8.5], [60., 60.], [3., 3.], [46., 53.], [3.5, 2]])
labels = torch.tensor([[1.], [1.], [1.], [1.], [1.], [0.], [0.], [0.], [0.]])

In [10]:
# model
model = NeuralNetworkModel()

# loss
loss_fn = nn.BCELoss()

# Optimizer
optimizer = SGD(model.parameters(), lr=0.0001)

for i in range(100000):
    # Zero your gradients for every batch!
    optimizer.zero_grad()

    # output of model
    outputs = model(inputs)
    
    loss = loss_fn(outputs, labels)
    loss.backward()

    optimizer.step()
    
    if i % 200 == 0:
        print(i)
        print(loss.item())
        # print('w Grad', torch.sum((inputs * (outputs - labels)) / 5))
        # print('b Grad', torch.sum((outputs - labels) / 5))
        print('---------')

0
4.689337253570557
---------
200
2.84749436378479
---------
400
1.666078805923462
---------
600
0.8643901348114014
---------
800
0.5856875777244568
---------
1000
0.47291266918182373
---------
1200
0.40351632237434387
---------
1400
0.35636603832244873
---------
1600
0.3225100636482239
---------
1800
0.2971487045288086
---------
2000
0.27747905254364014
---------
2200
0.2617771029472351
---------
2400
0.24893678724765778
---------
2600
0.23822037875652313
---------
2800
0.22911977767944336
---------
3000
0.2212745100259781
---------
3200
0.21442289650440216
---------
3400
0.208370178937912
---------
3600
0.20296898484230042
---------
3800
0.19810576736927032
---------
4000
0.19369179010391235
---------
4200
0.1896563172340393
---------
4400
0.18594308197498322
---------
4600
0.1825059950351715
---------
4800
0.17930763959884644
---------
5000
0.1763167381286621
---------
5200
0.17350737750530243
---------
5400
0.17095603048801422
---------
5600
0.16879242658615112
---------
5800
0.166

In [26]:
t = model(torch.tensor([[5., 5.]])).item()
("%.17f" % t).rstrip('0').rstrip('.')

'0.02306652069091797'

In [27]:
# Print weights
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[ 0.7368, -0.8874],
        [-0.4322,  0.4179],
        [-0.3870, -0.5734],
        [-0.5730, -0.6160],
        [-0.6488,  0.6514],
        [-0.0517,  0.5116],
        [ 0.1638,  0.5767],
        [ 0.3115,  0.4776],
        [-0.2639,  0.6246],
        [ 0.5427, -0.1011]], requires_grad=True)
Parameter containing:
tensor([ 0.1606,  0.2853, -0.5284,  0.1202,  0.3263, -0.0066,  0.6420,  0.7451,
        -0.5898,  0.1557], requires_grad=True)
Parameter containing:
tensor([[ 0.7652,  0.4596,  0.2977,  0.1444,  0.7010, -0.0960, -0.3343, -0.4086,
          0.2799, -0.1285]], requires_grad=True)
Parameter containing:
tensor([-0.5292], requires_grad=True)
