In [5]:
import torch

import torch.nn as nn
import numpy as np

from torch.optim import SGD

In [40]:
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.linear = nn.Linear(1, 1)
        # self.linear.weight.data.uniform_(-0.5,0.5)

    def forward(self, x):
        x = self.linear(x)

        return x

In [48]:
# data
inputs = torch.tensor([[2.], [3.], [4.], [6.], [7.]])
labels = torch.tensor([[70.], [110.], [165.], [390.], [550.]])

In [86]:
# model
model = LinearModel()

# loss
loss_fn = nn.MSELoss()

# Optimizer
optimizer = SGD(model.parameters(), lr=0.001, momentum=0.9)

for i in range(10000):
    # Zero your gradients for every batch!
    optimizer.zero_grad()

    # output of model
    outputs = model(inputs)
    
    loss = loss_fn(outputs, labels)
    loss.backward()

    optimizer.step()
    
    if i % 200 == 0:
        print(i)
        print(loss.item())
        print('w Grad', torch.sum((inputs * (outputs - labels)) / 5))
        print('b Grad', torch.sum((outputs - labels) / 5))
        print('---------')

0
98032.3515625
w Grad tensor(-1450.0605, grad_fn=<SumBackward0>)
b Grad tensor(-254.1657, grad_fn=<SumBackward0>)
---------
200
3039.235595703125
w Grad tensor(-2.9374, grad_fn=<SumBackward0>)
b Grad tensor(14.9546, grad_fn=<SumBackward0>)
---------
400
1924.3648681640625
w Grad tensor(-1.5965, grad_fn=<SumBackward0>)
b Grad tensor(8.2211, grad_fn=<SumBackward0>)
---------
600
1587.718505859375
w Grad tensor(-0.8775, grad_fn=<SumBackward0>)
b Grad tensor(4.5175, grad_fn=<SumBackward0>)
---------
800
1486.0667724609375
w Grad tensor(-0.4818, grad_fn=<SumBackward0>)
b Grad tensor(2.4825, grad_fn=<SumBackward0>)
---------
1000
1455.3709716796875
w Grad tensor(-0.2650, grad_fn=<SumBackward0>)
b Grad tensor(1.3641, grad_fn=<SumBackward0>)
---------
1200
1446.102294921875
w Grad tensor(-0.1456, grad_fn=<SumBackward0>)
b Grad tensor(0.7496, grad_fn=<SumBackward0>)
---------
1400
1443.303466796875
w Grad tensor(-0.0802, grad_fn=<SumBackward0>)
b Grad tensor(0.4119, grad_fn=<SumBackward0>)
---

KeyboardInterrupt: 

In [87]:
# Predict for 5
model(torch.tensor([[5.]]))

tensor([[315.1163]], grad_fn=<AddmmBackward0>)

In [78]:
# Print weights
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[96.8600]], requires_grad=True)
Parameter containing:
tensor([-169.1835], requires_grad=True)
