In [1]:
import torch

import torch.nn as nn
import numpy as np

from torch.optim import SGD

In [2]:
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.linear = nn.Linear(2, 1)

    def forward(self, x):
        x = self.linear(x)

        return x

In [3]:
# data
inputs = torch.tensor([[2., 4.], [3., 9.], [4., 16.], [6., 36.], [7., 49.]])
labels = torch.tensor([[70.], [110.], [165.], [390.], [550.]])

In [4]:
# model
model = LinearModel()

# loss
loss_fn = nn.MSELoss()

# Optimizer
optimizer = SGD(model.parameters(), lr=0.001, momentum=0.9)

for i in range(10000):
    # Zero your gradients for every batch!
    optimizer.zero_grad()

    # output of model
    outputs = model(inputs)
    
    loss = loss_fn(outputs, labels)
    loss.backward()

    optimizer.step()
    
    if i % 200 == 0:
        print(i)
        print(loss.item())
        print('w Grad', torch.sum((inputs * (outputs - labels)) / 5))
        print('b Grad', torch.sum((outputs - labels) / 5))
        print('---------')

0
89311.6015625
w Grad tensor(-9881.1094, grad_fn=<SumBackward0>)
b Grad tensor(-243.5826, grad_fn=<SumBackward0>)
---------
200
167.8958282470703
w Grad tensor(0.3736, grad_fn=<SumBackward0>)
b Grad tensor(-1.3273, grad_fn=<SumBackward0>)
---------
400
151.3308868408203
w Grad tensor(0.5547, grad_fn=<SumBackward0>)
b Grad tensor(-1.2511, grad_fn=<SumBackward0>)
---------
600
136.4982147216797
w Grad tensor(0.5230, grad_fn=<SumBackward0>)
b Grad tensor(-1.1839, grad_fn=<SumBackward0>)
---------
800
123.21639251708984
w Grad tensor(0.4974, grad_fn=<SumBackward0>)
b Grad tensor(-1.1202, grad_fn=<SumBackward0>)
---------
1000
111.32359313964844
w Grad tensor(0.4712, grad_fn=<SumBackward0>)
b Grad tensor(-1.0600, grad_fn=<SumBackward0>)
---------
1200
100.67411041259766
w Grad tensor(0.4441, grad_fn=<SumBackward0>)
b Grad tensor(-1.0031, grad_fn=<SumBackward0>)
---------
1400
91.13841247558594
w Grad tensor(0.4213, grad_fn=<SumBackward0>)
b Grad tensor(-0.9492, grad_fn=<SumBackward0>)
----

In [7]:
# Predict for 5
model(torch.tensor([[5., 25.]]))

tensor([[68.2442]], grad_fn=<AddmmBackward0>)

In [8]:
# Print weights
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[-43.7394,  15.4762]], requires_grad=True)
Parameter containing:
tensor([96.5074], requires_grad=True)
