In [1]:
import torch

import torch.nn as nn
import numpy as np

from torch.optim import SGD

In [27]:
class LogisticModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        # print('@@@@@')
        # print(x)
        x = self.linear(x)
        # print(x)
        x = nn.functional.sigmoid(x)
        # print(x)
        # print('@@@@@')

        return x

In [28]:
# data
inputs = torch.tensor([[1., 28., 4.], [1., 60., 34.], [1., 25., 3.], [0., 54., 20.], [0., 24., 2.], [0., 39., 12.], [0., 30., 4.], [1., 36., 10.], [1., 26., 1.], [0., 44., 9.]])
labels = torch.tensor([[1.], [1.], [1.], [1.], [1.], [1.], [1.], [0.], [0.], [0.]])

In [ ]:
# model
model = LogisticModel()

# loss
loss_fn = nn.BCELoss()

# Optimizer
optimizer = SGD(model.parameters(), lr=0.001, momentum=0.9)

for i in range(50000):
    # Zero your gradients for every batch!
    optimizer.zero_grad()

    # output of model
    outputs = model(inputs)
    
    loss = loss_fn(outputs, labels)
    loss.backward()

    optimizer.step()
    
    if i % 200 == 0:
        print(i)
        print(loss.item())
        # print('w Grad', torch.sum((inputs * (outputs - labels)) / 5))
        # print('b Grad', torch.sum((outputs - labels) / 5))
        print('---------')

0
21.52492332458496
---------
200
0.6120383143424988
---------
400
0.6060253381729126
---------
600
0.6006913185119629
---------
800
0.5959044098854065
---------
1000
0.591558575630188
---------
1200
0.5875686407089233
---------
1400
0.5838662981987
---------
1600
0.5803976058959961
---------
1800
0.5771190524101257
---------
2000
0.5739964246749878
---------
2200
0.5710026621818542
---------
2400
0.5681161284446716
---------
2600
0.5653196573257446
---------
2800
0.5625998377799988
---------
3000
0.5599458813667297
---------
3200
0.5573493242263794
---------
3400
0.5548032522201538
---------
3600
0.5523024797439575
---------
3800
0.5498424768447876
---------
4000
0.5474199056625366
---------
4200
0.5450320243835449
---------
4400
0.542676568031311
---------
4600
0.5403517484664917
---------
4800
0.5380558967590332
---------
5000
0.5357879996299744
---------
5200
0.5335469841957092
---------
5400
0.5313318967819214
---------
5600
0.5291420221328735
---------
5800
0.5269768834114075
---

In [26]:
# model(torch.tensor([[1., 49., 8.]]))
model(torch.tensor([[0., 29., 3.]]))

tensor([[0.9098]], grad_fn=<SigmoidBackward0>)

In [24]:
# Print weights
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[-0.9065, -0.1008,  0.2064]], requires_grad=True)
Parameter containing:
tensor([2.9719], requires_grad=True)
