In [1]:
import torch

In [4]:
out = torch.tensor ([[0.0, 0.0, 1.0]])
out_logits = torch.tensor ([[-1.e6, -1.e6, 1.e6]])

print(torch.softmax (out_logits, 1))
print(torch.softmax (out, 1))
# tensor([[0., 1., 0.]])
target = torch.argmax (out, dim = 1)
print(target)
# tensor([1])
print(torch.nn.CrossEntropyLoss() (out, target))
# tensor(0.5514)
print(torch.nn.CrossEntropyLoss() (out_logits, target))
# tensor(0.)

tensor([[0., 0., 1.]])
tensor([[0.2119, 0.2119, 0.5761]])
tensor([2])
tensor(0.5514)
tensor(0.)
