In [1]:
import torch

import torch.nn as nn
import numpy as np

from torch.optim import SGD

In [14]:
class LogisticModel(nn.Module):
    def __init__(self, input_size):
        super().__init__()

        self.linear = nn.Linear(input_size, 1)

    def forward(self, x):
        x = self.linear(x)
        x = nn.functional.sigmoid(x)
        
        return x

In [15]:
vocabulary_size = 0
word2location = {}

def prepare_vocabulary(data):
    idx = 0
    for sentence in data:
        for word in sentence.split():
            if word not in word2location:
                word2location[word] = idx
                idx += 1
    return idx

def convert2vec(sentence):
    res_vec = np.zeros(vocabulary_size)
    for word in sentence.split():
        if word in word2location:
            res_vec[word2location[word]] += 1

    return res_vec

data = ["Where are you? I'm trying to reach you for half an hour already, contact me ASAP I need to leave now!",
        "I want to go out for lunch, let me know in the next couple of minutes if you would like to join.",
        "I was wondering whether you are planning to attend the party we are having next month.",
        "I wanted to share my thought with you."]

vocabulary_size = prepare_vocabulary(data)

In [19]:
inputs = torch.FloatTensor([convert2vec(data[0]), convert2vec(data[1]), convert2vec(data[2]), convert2vec(data[3])])
labels = torch.FloatTensor([[1], [1], [0], [0]])

In [20]:
# model
model = LogisticModel(vocabulary_size)

# loss
loss_fn = nn.BCELoss()

# Optimizer
optimizer = SGD(model.parameters(), lr=0.00001)

for i in range(10000):
    # Zero your gradients for every batch!
    optimizer.zero_grad()

    # output of model
    outputs = model(inputs)
    
    loss = loss_fn(outputs, labels)
    loss.backward()

    optimizer.step()
    
    if i % 200 == 0:
        print(i)
        print(loss.item())
        print('---------')

0
0.660953164100647
---------
200
0.6592991352081299
---------
400
0.6576524972915649
---------
600
0.6560136675834656
---------
800
0.6543826460838318
---------
1000
0.6527591347694397
---------
1200
0.6511423587799072
---------
1400
0.6495336890220642
---------
1600
0.6479319334030151
---------
1800
0.646338164806366
---------
2000
0.6447509527206421
---------
2200
0.6431711912155151
---------
2400
0.6415989995002747
---------
2600
0.6400336623191833
---------
2800
0.6384761333465576
---------
3000
0.6369247436523438
---------
3200
0.6353808641433716
---------
3400
0.6338437795639038
---------
3600
0.6323136687278748
---------
3800
0.6307904720306396
---------
4000
0.6292738914489746
---------
4200
0.627764105796814
---------
4400
0.6262615323066711
---------
4600
0.6247653961181641
---------
4800
0.623275637626648
---------
5000
0.6217929124832153
---------
5200
0.6203165650367737
---------
5400
0.618847131729126
---------
5600
0.6173836588859558
---------
5800
0.6159263253211975
--

In [23]:
print(model(torch.FloatTensor(convert2vec("I need you now! Please answer ASAP!"))))
print(model(torch.FloatTensor(convert2vec("I wanted to hear your thoughts about my plans."))))

tensor([0.5339], grad_fn=<SigmoidBackward0>)
tensor([0.4837], grad_fn=<SigmoidBackward0>)


In [24]:
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[ 0.0470, -0.0672,  0.0568,  0.0685, -0.0417,  0.0971,  0.0850,  0.1281,
         -0.0225, -0.0430, -0.0765, -0.0849,  0.0028,  0.1283, -0.0007, -0.0007,
         -0.0517, -0.0241,  0.0273,  0.1143,  0.0379, -0.0968, -0.0995, -0.0844,
          0.0095, -0.0046, -0.0313,  0.1256, -0.0683,  0.1363, -0.0686,  0.0506,
          0.0714,  0.0023, -0.0800,  0.1329,  0.0266, -0.1091,  0.0265, -0.0387,
          0.1082,  0.0157, -0.0351, -0.0139, -0.1442, -0.0043, -0.0636, -0.0760,
         -0.0093,  0.0235, -0.0455]], requires_grad=True)
Parameter containing:
tensor([-0.0306], requires_grad=True)
